name: Deploy to Cloudflare Pages (Wrangler CLI)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages using Wrangler CLI
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          NEXT_PUBLIC_CLOUDFLARE_BASE_URL: ${{ secrets.CLOUDFLARE_BASE_URL }}
          NEXT_PUBLIC_SITE_URL: ${{ secrets.SITE_URL }}

      - name: Install Wrangler
        run: npm install -g wrangler

      # 注意：确保在GitHub仓库中设置了以下Secrets:
      # 1. CLOUDFLARE_API_TOKEN - 从Cloudflare控制面板"我的个人资料 > API令牌"中创建
      - name: Deploy to Cloudflare Pages with Wrangler
        run: |
          echo "${{ secrets.CLOUDFLARE_API_TOKEN }}" | wrangler login
          wrangler pages deploy out --project-name=winuc --branch=main
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }} 